### ISSUE TITLE
RTD root path leads to old docs

### ISSUE THREAD

**Issue by frewsxcv** [tweepy/tweepy.github.com#5]
Steps to reproduce
1. Navigate to: http://tweepy.readthedocs.org/
2. Get redirected to: https://tweepy.readthedocs.org/en/v3.2.0/

What should have happened:
1. Navigate to: http://tweepy.readthedocs.org/
2. Get redirected to: https://tweepy.readthedocs.org/en/v3.4.0/ or https://tweepy.readthedocs.org/en/stable/

**Comment by Harmon758** [comment]
It now redirects to http://tweepy.readthedocs.io/en/v3.5.0/ instead of https://tweepy.readthedocs.io/en/v3.6.0/ or https://tweepy.readthedocs.io/en/stable/.

**Comment by Harmon758** [comment]
This is now resolved, as the Default Version for Read the Docs is now `latest`, meaning http://tweepy.readthedocs.org/ now redirects to https://tweepy.readthedocs.io/en/latest/.
